### ISSUE TITLE
Error running PStrain_V30.py script

### ISSUE THREAD

**Issue by sahilrishav2** [wshuai294/PStrain#13]
Hello,

I am running PStrain_V30.py script on test dataset but it is showing an error:

> Could not build fai index test_dir/test//ref//merged_ref.fa.fai

This is the complete report:

> python3 PStrain_V30.py --metaphlan3 /home/rishav/.local/bin/metaphlan --dbdir_V30 ../db_V30 -c ../test/config.txt -o test_dir --bowtie2 /home/rishav/anaconda3/envs/biobakery3/bin/bowtie2 --bowtie2-build /home/rishav/anaconda3/envs/biobakery3/bin/bowtie2-build  --samtools /home/rishav/anaconda3/envs/biobakery3/bin/samtools --picard /home/rishav/anaconda3/envs/biobakery3/bin/picard --gatk /home/rishav/anaconda3/envs/biobakery3/bin/gatk 
> Start Profiling test...
> [faidx] Could not build fai index test_dir/test//ref//merged_ref.fa.fai
> Settings:
>   Output files: "test_dir/test//ref//merged_ref.*.bt2"
>   Line rate: 6 (line is 64 bytes)
>   Lines per side: 1 (side is 64 bytes)
>   Offset rate: 4 (one in 16)
>   FTable chars: 10
>   Strings: unpacked
>   Max bucket size: default
>   Max bucket size, sqrt multiplier: default
>   Max bucket size, len divisor: 4
>   Difference-cover sample period: 1024
>   Endianness: little
>   Actual local endianness: little
>   Sanity checking: disabled
>   Assertions: disabled
>   Random seed: 0
>   Sizeofs: void*:8, int:4, long:8, size_t:8
> Input files DNA, FASTA:
>   test_dir/test//ref//merged_ref.fa
> Warning: Empty fasta file: 'test_dir/test//ref//merged_ref.fa'
> Warning: All fasta inputs were empty
> Total time for call to driver() for forward index: 00:00:00
> Error: Encountered internal Bowtie 2 exception (#1)
> Command: /home/rishav/anaconda3/envs/biobakery3/bin/bowtie2-build-s --wrapper basic-0 -f test_dir/test//ref//merged_ref.fa test_dir/test//ref//merged_ref 
> (ERR): "test_dir/test//ref//merged_ref" does not exist or is not a Bowtie 2 index
> Exiting now ...
> [main_samview] fail to read the header from "-".
> [W::hts_set_opt] Cannot change block size for this format
> samtools sort: failed to read header from "-"
> Error: Invalid or corrupt jarfile /home/rishav/anaconda3/envs/biobakery3/bin/picard
> rm: cannot remove 'test_dir/test//map/mapped.sort.bam': No such file or directory
> [E::hts_open_format] Failed to open file "test_dir/test//map/mapped.bam" : No such file or directory
> samtools index: failed to open "test_dir/test//map/mapped.bam": No such file or directory
> [E::hts_open_format] Failed to open file "test_dir/test//map/mapped.bam" : No such file or directory
> samtools depth: Cannot open input file "test_dir/test//map/mapped.bam": No such file or directory
> Error: Invalid or corrupt jarfile /home/rishav/anaconda3/envs/biobakery3/bin/gatk
> [E::hts_open_format] Failed to open file "test_dir/test//map/mapped.vcf.gz" : No such file or directory
> No need to merge in case of one sample.

Kindly help me with this concern. 
Thank you

**Comment by sahilrishav2** [comment]
I have resolved the above issue but again new issue came:

`python3 PStrain_V30.py --metaphlan3 /home/rishav/.local/bin/metaphlan --dbdir_V30 ../db_V30 -c ../test/config.txt -o test_dir --bowtie2 /usr/bin/bowtie2 --bowtie2-build /usr/bin/bowtie2-build  --samtools /home/rishav/anaconda3/envs/biobakery3/bin/samtools --picard /home/rishav/packages/picard-tools-2.1.0/picard.jar --gatk /home/rishav/packages/GATK_3.5/GenomeAnalysisTK.jar`

> 
> 256979 pairs aligned 0 times concordantly or discordantly; of these:
>       513958 mates make up the pairs; of these:
>         513451 (99.90%) aligned 0 times
>         507 (0.10%) aligned exactly 1 time
>         0 (0.00%) aligned >1 times
> 0.34% overall alignment rate
> [Fri Apr 26 16:30:01 IST 2024] picard.sam.AddOrReplaceReadGroups INPUT=test_dir/test//map/mapped.sort.bam OUTPUT=test_dir/test/map/mapped.bam RGLB=whatever RGPL=illumina RGPU=whatever RGSM=whatever    RGID=1 VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json
> [Fri Apr 26 16:30:01 IST 2024] Executing as rishav@mjlab-Precision-7920-Tower on Linux 6.5.0-27-generic amd64; OpenJDK 64-Bit Server VM 17.0.3-internal+0-adhoc..src; Picard version: 2.1.0(25ebc07f7fbaa7c1a4a8e6c130c88c1d10681802_1454776546) JdkDeflater
> INFO	2024-04-26 16:30:01	AddOrReplaceReadGroups	Created read group ID=1 PL=illumina LB=whatever SM=whatever
> 
> [Fri Apr 26 16:30:02 IST 2024] picard.sam.AddOrReplaceReadGroups done. Elapsed time: 0.00 minutes.
> Runtime.totalMemory()=2181038080
> ##### ERROR ------------------------------------------------------------------------------------------
> ##### ERROR A USER ERROR has occurred (version 3.5-0-g36282e4): 
> ##### ERROR
> ##### ERROR This means that one or more arguments or inputs in your command are incorrect.
> ##### ERROR The error message below tells you what is the problem.
> ##### ERROR
> ##### ERROR If the problem is an invalid argument, please check the online documentation guide
> ##### ERROR (or rerun your command with --help) to view allowable command-line arguments for this tool.
> ##### ERROR
> ##### ERROR Visit our website and forum for extensive documentation and answers to 
> ##### ERROR commonly asked questions http://www.broadinstitute.org/gatk
> ##### ERROR
> ##### ERROR Please do NOT post this error to the GATK forum unless you have really tried to fix it yourself.
> ##### ERROR
> ##### ERROR MESSAGE: Invalid command line: Malformed walker argument: Could not find walker with name: HaplotypeCaller
> ##### ERROR ------------------------------------------------------------------------------------------
> [E::hts_open_format] Failed to open file "test_dir/test//map/mapped.vcf.gz" : No such file or directory
> No need to merge in case of one sample.

**Comment by wshuai294** [comment]
Hello, how did you resolve the first issue? It seems that no read is mapped to the reference.

**Comment by sahilrishav2** [comment]
Actually, the previous problem was coming from bowtie2 . Bowtie2 was not properly installed

**Comment by sahilrishav2** [comment]
This problem is however from GATK. I am unable to solve it. Kindly help me

**Comment by wshuai294** [comment]
Is the file `test_dir/test//ref//merged_ref.fa` empty? How about the content in the metaphlan3 output and the bam file? I guess the problem is not caused by GATK. Because no reads are mapped successfully, seen from
```
256979 pairs aligned 0 times concordantly or discordantly; of these:
513958 mates make up the pairs; of these:
513451 (99.90%) aligned 0 times
507 (0.10%) aligned exactly 1 time
0 (0.00%) aligned >1 times
0.34% overall alignment rate
```

**Comment by wshuai294** [comment]
I am more than happy to help you with this issue. Now I am trying to reproduce this error.

**Comment by sahilrishav2** [comment]
Yaa, now, I get it. Currently, i am just running the test datasets provided by you as a checking process. So, i want to ask if the command that i am running is working well ? could i use this on my real data

**Comment by wshuai294** [comment]
I guess there is some error. Your metaphlan3 output might be empty. I guess there might be a problem with your metaphlan. Is the version of `/home/rishav/.local/bin/metaphlan` methphlan3?

**Comment by sahilrishav2** [comment]
One more thing i want to say that i am using metaphlan4 and metaphlan4 database

**Comment by wshuai294** [comment]
there might be a problem because, in this case, the metaphlan output is inconsistent with `--dbdir_V30 ../db_V30`.

**Comment by sahilrishav2** [comment]
So, isn't there a way to use it with metaphlan4

**Comment by wshuai294** [comment]
Currently, it cannot. But if you need this, I will try to update it to support metaphlan4.

**Comment by sahilrishav2** [comment]
Actually, i am performing benchmarking of some tools in which i have included PStrain also. So, it would be better if you upgrade it to support MetaPhlan4, so that i could use this tool in its best way.

**Comment by wshuai294** [comment]
Ok, Great to hear this. I will upgrade it soon. Also, I will prepare a conda env to make it easier to install.

**Comment by sahilrishav2** [comment]
Thank you so much for your support

**Comment by wshuai294** [comment]
Hello, I am glad to inform you that PStrain supports Metaphlan 4 now. I also provided the conda environment to easily use it. Please follow this:

First, get the source code and construct the env
```
git clone https://github.com/wshuai294/PStrain.git --depth 1
cd PStrain/
conda env create --name pstrain -f pstrain_metaphlan4_env.yml
conda activate pstrain
```
Then get the metaphlan database. If you have the database already, you can skip this step, and pass the database folder and index to `PStrain.py` by `--bowtie2db` and `-x` (same as the Metaphlan parameter).
```
bash scripts/collect_metaphlan_datbase.sh -x mpa_vOct22_CHOCOPhlAnSGB_202403 -m 4 -d ./   #constructing the database for Metaphlan4 
```
Finally, test PStrain by:
```
python3 scripts/PStrain.py --help
cd test/
bash test_PStrain_V40.sh  # use Metaphlan 4, remember edit the --bowtie2db and -x if you have downloaded the database yourself.
```
Thank you so much for benchmarking our method. Please feel free to ask me if you have any further queries.

**Comment by sahilrishav2** [comment]
Thank you so much for your support. We will inform you whenever our paper goes in the communication process.

**Comment by wshuai294** [comment]
Hello, I have fixed a bug related to missing NCBI_ID in the Metaphlan results. This bug was causing the process to be terminated during execution. Please pull the latest commit to get the fix. Apologies for any inconvenience caused.

**Comment by sahilrishav2** [comment]
Ok, thank you. Actually, I have not run the tool yet. Currently, i am doing standardization of some other tools also. I will get back to you if any issues persist. Thank you once again
